export const mapStyles = [
  { featureType: 'all', elementType: 'geometry', stylers: [{ color: '#E8E8E5' }] },
  { featureType: 'all', elementType: 'geometry.stroke', stylers: [{ color: '#D0D0CC' }] },
  { featureType: 'all', elementType: 'labels.text.fill', stylers: [{ color: '#6B6B6B' }] },
  { featureType: 'all', elementType: 'labels.text.stroke', stylers: [{ color: '#F7F7F5' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#D0D0CC' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#4A4A4A' }] },
  { featureType: 'landscape', elementType: 'geometry', stylers: [{ color: '#EDEDEA' }] },
  { featureType: 'landscape.natural', elementType: 'all', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi', elementType: 'all', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.park', elementType: 'all', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#D0D0CC' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#D8D8D4' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#C0C0BC' }] },
  { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#E0E0DC' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#D0D8DC' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#A0A0A0' }] },
];